[theme]
primaryColor = "#AA4A44" # example for buttons and highlights
backgroundColor = "#EAEBF8"
secondaryBackgroundColor = "#C4C7EB" # example for the sidebar
textColor = "#473C4F"
font = "sans serif"